const FLIP_CARD = 'FLIP_CARD';
const RESTART_GAME = 'RESTART_GAME';
const CHANGE_ROUTE = 'CHANGE_ROUTE';
const HIDE_UNMATCHED = 'HIDE_UNMATCHED';
const SOLVE_MATCHED = 'SOLVE_MATCHED';
export default { FLIP_CARD, HIDE_UNMATCHED, SOLVE_MATCHED, RESTART_GAME, CHANGE_ROUTE };
